version: "3.9"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend-prod
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: frontend-prod
    ports:
      - "80:80"
